config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'inputs#index'
  get "error", to:"inputs#error"
  resources :inputs


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
class Battle < ApplicationRecord

validates :ballistic_skill, :armour, :inclusion => 2..7
validates :attack_models, :shots, :weapon_strength, :damage, :defend_models, :toughness, :leadership, :times_run, numericality: { other_than: 0 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    
  end

end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  require 'gchart'
  require 'battleround.rb'
  include BattleRound

  def index
    @battle = Battle.new
  end

  def create
    @battle = Battle.new(battle_params)
    battle_results
    @battle.total_rounds = @total_rounds
    if @battle.save
      redirect_to action: "show", id: @battle.id
    else
      error_message = @battle.errors.full_messages.join(',')
      redirect_to action: "error"
    end
  end

  def show
    @showing_result = Battle.find(params[:id])
    aggregation(@showing_result[:total_rounds])
  end

  def error

  end

  private

  def battle_params
    params.permit(
      :attack_models,
      :shots,
      :d3,
      :d6,
      :ballistic_skill,
      :weapon_strength,
      :damage,
      :d3_damage,
      :d6_damage,
      :ap_value,
      :defend_models,
      :toughness,
      :wounds,
      :armour,
      :invulnerable,
      :leadership,
      :plasma,
      :sniper,
      :always_hit,
      :neg1_to_hit_attack,
      :neg1_to_hit_defend,
      :plus1_to_hit,
      :times_run,
      :reroll_hits,
      :reroll1_hits,
      :reroll_wounds,
      :reroll1_wounds
    )
  end

  def battle_results
    @total_rounds = []
    @times_run = params["times_run"].to_i
    while @times_run > 0
      battle(battle_params)
      @times_run -=1
      @total_rounds << @round
    end
  end

  def aggregation(array)
    @final_hash = {}
    array.sort.each do |number|
      @final_hash.store(number,array.count(number))
    end
    @final_hash.sort
    @highest = @final_hash.values.sort.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inputs/error.html.erb
<h1>Some aspect of your battle was filled out incorrectly. Please Go back and try again!</h1>

<button onclick="goBack()">Try Again</button>

app/views/inputs/index.html.erb
<h1>Enter your data</h1>

<%= form_tag inputs_path @battle do %>
<h2>
  Attacking Unit
</h2>
  <%= label_tag "Attacking Models" %> <br />
  <%= number_field_tag "attack_models", 1 %><br />

  <%= label_tag "Attacks" %> <br />
  <%= number_field_tag "shots", 1 %><br />
  <%= check_box_tag "d3" %>
  <%= label_tag "D3 Attacks" %>
  <%= check_box_tag "d6" %>
  <%= label_tag "D6 Attacks" %><br />

  <%= label_tag "Ballistic Skill" %> <br />
  <%= number_field_tag "ballistic_skill" %><br />

  <%= label_tag "Weapon Strength" %> <br />
  <%= number_field_tag "weapon_strength" %><br />

  <%= label_tag "Damage" %> <br />
  <%= number_field_tag "damage", 1 %><br />
  <%= check_box_tag "d3_damage" %>
  <%= label_tag "D3 Damage" %>
  <%= check_box_tag "d6_damage" %>
  <%= label_tag "D6 Damage" %><br />

  <%= label_tag "AP Value" %> <br />
  -<%= number_field_tag "ap_value", 0%><br />

<hr />

<h2>
  Defending Unit
</h2>
  <%= label_tag "Defending Models" %> <br />
  <%= number_field_tag "defend_models", 1 %><br />

  <%= label_tag "Toughness" %> <br />
  <%= number_field_tag "toughness" %><br />

  <%= label_tag "Wounds" %> <br />
  <%= number_field_tag "wounds", 1 %><br />

  <%= label_tag "Armour Save" %> <br />
  <%= number_field_tag "armour" %><br />

  <%= label_tag "Invulnerable Save" %> <br />
  <%= number_field_tag "invulnerable", 0 %><br />

  <%= label_tag "Leadership Value" %> <br />
  <%= number_field_tag "leadership" %><br />
<hr />

<h2> Modifiers </h2>
<%= check_box_tag "plasma" %>
<%= label_tag "Plasma Supercharge" %> <br />

<%= check_box_tag "sniper" %>
<%= label_tag "Sniper Rifle" %><br />

<%= check_box_tag "neg1_to_hit_attack" %>
<%= label_tag "-1 to Hit(attacking models)" %> <br />

<%= check_box_tag "neg1_to_hit_defend" %>
<%= label_tag "-1 to Hit(defending models)" %> <br />

<%= check_box_tag "plus1_to_hit" %>
<%= label_tag "+1 to Hit" %> <br />

<%= check_box_tag "always_hit" %>
<%= label_tag "This weapon always hits" %> <br />

<%= check_box_tag "reroll_hits" %>
<%= label_tag "Reroll all failed to hit rolls" %> </br>

<%= check_box_tag "reroll1_hits" %>
<%= label_tag "Reroll all 1s to hit rolls" %> </br>

<%= check_box_tag "reroll_wounds" %>
<%= label_tag "Reroll all failed to wound rolls" %> </br>

<%= check_box_tag "reroll1_wounds" %>
<%= label_tag "Reroll all 1s to wound rolls" %> </br>

<hr />

  <%= label_tag "Number of Complete kills" %> <br />
  <%= number_field_tag "times_run" %><br />

  <%= submit_tag "Begin Battle" %>
<% end %><br />

app/views/inputs/show.html.erb
<h1>Chart</h1>


  <% if !@final_hash.nil? %>
    <img src="<%= Gchart.bar(:data => @final_hash.values, :labels => @final_hash.keys, :axis_with_labels => 'y', :max_value => @highest, :min_value => 0, :size => '250x250') %>" />
  <% end %>



  <h1>Mean: Median: Mode</h1>
  <p><% @final_hash.each do |round| %>
    <%= round %>
    <% end unless @total_rounds.nil? %>
  </p>

  <% if !@died_to_plasma.nil? && @died_to_plasma > 0 %>
    <h1>Number of Models lost to Plasma</h1>
    <p><%= @died_to_plasma %></p>
    <% end %>

    <!-- <button type="button" onclick="location.reload()">Fight Again</button><br /> -->

<button onclick="goBack()">Change Units</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BattleRound</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <script>
    function goBack() {
        window.history.back();
    }
    </script>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Enter your data</h1>

<%= form_tag static_pages_path @battle do %>
<h2>
  Attacking Unit
</h2>
  <%= label_tag "Attacking Models" %> <br />
  <%= number_field_tag "attack_models" %><br />

  <%= label_tag "Shots" %> <br />
  <%= number_field_tag "shots" %><br />

  <%= label_tag "Ballistic Skill" %> <br />
  <%= number_field_tag "ballistic_skill" %><br />

  <%= label_tag "Weapon Strength" %> <br />
  <%= number_field_tag "weapon_strength" %><br />

  <%= label_tag "Damage" %> <br />
  <%= number_field_tag "damage" %><br />

  <%= label_tag "AP Value" %> <br />
  <%= number_field_tag "ap_value" %><br />

<hr />
<h2>
  Defending Unit
</h2>
  <%= label_tag "Defending Models" %> <br />
  <%= number_field_tag "defend_models" %><br />

  <%= label_tag "Toughness" %> <br />
  <%= number_field_tag "toughness" %><br />

  <%= label_tag "Wounds" %> <br />
  <%= number_field_tag "wounds" %><br />

  <%= label_tag "Armour Save" %> <br />
  <%= number_field_tag "armour" %><br />

  <%= label_tag "Invulnerable Save" %> <br />
  <%= number_field_tag "invulnerable" %><br />
<hr />
<h2> Modifiers </h2>
<%= label_tag "-1 to Hit(attacking models)" %> <br />
<%= check_box_tag "neg1_to_hit_attack" %><br />

<%= label_tag "-1 to Hit(defending models)" %> <br />
<%= check_box_tag "neg1_to_hit_defend" %><br />

<%= label_tag "+1 to Hit" %> <br />
<%= check_box_tag "plus1_to_hit" %><br />

<hr />

  <%= label_tag "Number of Complete kills" %> <br />
  <%= number_field_tag "times_run" %><br />

  <%= submit_tag "Go!" %>
<% end %>





<h1>Chart</h1>
<% if !@final_array.nil? %>
<img src="<%= Gchart.bar(:data => @final_array.values , :labels => @final_array.keys, :axis_with_labels => 'y') %>" />
<% end %>



<h1>Raw numbers</h1>
<p><% @total_rounds.each do |round| %>
  <%= round %>
  <% end unless @total_rounds.nil? %>
</p>